name: scan-cve

on:
  workflow_dispatch:
  push:
    branches: [ "master", "dev" ]
  pull_request:
    branches: [ "master", "dev" ]
  schedule:
    - cron: "03 */24 * * *"

permissions:
  contents: read

jobs:

  scan:
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
    - uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5

    - name: Set up Go
      uses: actions/setup-go@44694675825211faa026b3c33043df3e48a5fa00 # v6
      with:
        # renovate: datasource=golang-version depName=golang
        go-version: '1.24.6'

    - name: Install govulncheck
      run: go install golang.org/x/vuln/cmd/govulncheck@latest

    - name: Run govulncheck for project
      run: govulncheck -show verbose -scan module

    - name: Build binary
      run: make build-via-docker

    - name: Run govulncheck for binary
      run: govulncheck -mode=binary -show verbose -scan module ./ptcpdump
